[build]
  command = "npm run build"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  URL = "https://celebrated-kashata-7d0682.netlify.app/"
