[build]
  command = "npm start"
  publish = "public"

[dev]
  command = "npm start"

[[redirects]]
  from = "/socket.io/*"
  to = "https://celebrated-kashata-7d0682.netlify.app/:splat"
  status = 200
  force = true
